// Generated by CoffeeScript 2.7.0
(function() {
  var BORDERS, CELL_SIZE, GameCell, GameJelly, GameState, Stage, Wall, i, k, level, levelPicker, levels, moveToCell, option, ref, stage, undoHandler,
    indexOf = [].indexOf;

  levels = [
    // Level 1
    ["xxxxxxxxxxxxxx",
    "x            x",
    "x            x",
    "x      r     x",
    "x      xx    x",
    "x  g     r b x",
    "xxbxxxg xxxxxx",
    "xxxxxxxxxxxxxx"],
    ["xxxxxxxxxxxxxx",
    "x            x",
    "x            x",
    "x            x",
    "x     g   g  x",
    "x   r r   r  x",
    "xxxxx x x xxxx",
    "xxxxxxxxxxxxxx"],
    ["xxxxxxxxxxxxxx",
    "x            x",
    "x            x",
    "x   bg  x g  x",
    "xxx xxxrxxx  x",
    "x      b     x",
    "xxx xxxrxxxxxx",
    "xxxxxxxxxxxxxx"],
    ["xxxxxxxxxxxxxx",
    "x            x",
    "x       r    x",
    "x       b    x",
    "x       x    x",
    "x b r        x",
    "x b r      b x",
    "xxx x      xxx",
    "xxxxx xxxxxxxx",
    "xxxxxxxxxxxxxx"],
    // Level 5
    ["xxxxxxxxxxxxxx",
    "x            x",
    "x            x",
    "xrg  gg      x",
    "xxx xxxx xx  x",
    "xrg          x",
    "xxxxx  xx   xx",
    "xxxxxx xx  xxx",
    "xxxxxxxxxxxxxx"],
    ["xxxxxxxxxxxxxx",
    "xxxxxxx      x",
    "xxxxxxx g    x",
    "x       xx   x",
    "x r   b      x",
    "x x xxx x g  x",
    "x         x bx",
    "x       r xxxx",
    "x   xxxxxxxxxx",
    "xxxxxxxxxxxxxx"],
    [
      // Anchored jellies are specified separately after the
      // level map. Instead of [row, row, row...in the presence of
      // anchors the level specification is: 
      // [ [row,row,row...], [ anchor, anchor, anchor...] ].
      // Each anchor starts from a colored non-black jelly's
      // coordinates and specifies the direction in which it's "held".
      ["xxxxxxxxxxxxxx",
      "x            x",
      "x          r x",
      "x          x x",
      "x     b   b  x",
      "x     x  rr  x",
      "x         x  x",
      "x r  bx x x  x",
      "x x  xx x x  x",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 2,
          y: 7,
          dir: 'down'
        },
        {
          x: 5,
          y: 7,
          dir: 'down'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "xxxx x  x xxxx",
      "xxx  g  b  xxx",
      "xx   x  x   xx",
      "xx   b  g   xx",
      "xxg        bxx",
      "xxxg      bxxx",
      "xxxx      xxxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 5,
          y: 4,
          dir: 'up'
        },
        {
          x: 8,
          y: 4,
          dir: 'up'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "x            x",
      "x            x",
      "x          rbx",
      "x    x     xxx",
      "xb        00xx",
      "xx  rx  x xxxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 4,
          y: 6,
          dir: 'down'
        }
      ]
    ],
    [
      // Level 10
      ["xxxxxxxxxxxxxx",
      "x   gr       x",
      "x   00 1     x",
      "x    x x xxxxx",
      "x            x",
      "x  x  x      x",
      "x        x  rx",
      "xx   x     gxx",
      "x          xxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 11,
          y: 7,
          dir: 'down'
        },
        {
          x: 12,
          y: 6,
          dir: 'down'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "x      g00g gx",
      "x       xxx xx",
      "x           gx",
      "x11         xx",
      "xxx          x",
      "x       g    x",
      "x   x xxx   gx",
      "x   xxxxxx xxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 12,
          y: 7,
          dir: 'down'
        },
        {
          x: 7,
          y: 1,
          dir: 'right'
        },
        {
          x: 10,
          y: 1,
          dir: 'left'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "xxr rr  rr rxx",
      "xxx  x  x  xxx",
      "x            x",
      "xb          bx",
      "xx          xx",
      "x            x",
      "x            x",
      "x   xxxxxx   x",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 12,
          y: 4,
          dir: 'down'
        }
      ]
    ],
    ["xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxx",
    "xxxxx gr xxxxx",
    "xxxxx rb xxxxx",
    "xxxxx gr xxxxx",
    "xxxxx bg xxxxx",
    "xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxx"],
    [
      ["xxxxxxxxxxxxxx",
      "xxxxxxxxx   rx",
      "xxxxxxxxx   gx",
      "xxxxxxxxx   gx",
      "x1122       gx",
      "x1122       gx",
      "x0033      xxx",
      "x0033      xxx",
      "xxr x gxxx xxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 2,
          y: 8,
          dir: 'down'
        },
        {
          x: 6,
          y: 8,
          dir: 'down'
        }
      ]
    ],
    [
      // Level 15
      ["xxxxxxxxxxxxxx",
      "xr r r      rx",
      "xg x x      gx",
      "xb          bx",
      "xxxxx     xxxx",
      "xxxxxx   xxxxx",
      "xxxxxx   xxxxx",
      "xxxxxx   xxxxx",
      "xxxxxxgggxxxxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 1,
          y: 3,
          dir: 'down'
        },
        {
          x: 6,
          y: 8,
          dir: 'left'
        },
        {
          x: 8,
          y: 8,
          dir: 'right'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "xx   0001233rx",
      "xx   0411233xx",
      "xx   444122xxx",
      "xx     xxxxxxx",
      "xr     xxxxxxx",
      "xx     xxxxxxx",
      "xx     xxxxxxx",
      "xx     xxxxxxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 1,
          y: 5,
          dir: 'up'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "xxxx000xxxgb x",
      "xxxx0     bg x",
      "xxxx0    11xxx",
      "xxxx000xxxxxxx",
      "x 222  xxxxxxx",
      "xxxx     xxgxx",
      "xxxx   g    bx",
      "xxxx   x     x",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 11,
          y: 6,
          dir: 'up'
        },
        {
          x: 12,
          y: 7,
          dir: 'up'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "x            x",
      "xb01         x",
      "xb0gg     g  x",
      "xb023     g4bx",
      "xxxxx g   xxxx",
      "xxxxx gg  xxxx",
      "xxxxx ggg xxxx",
      "xxxxx ggggxxxx",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 12,
          y: 4,
          dir: 'down'
        }
      ]
    ],
    [
      ["xxxxxxxxxxxxxx",
      "xg0    g1gx  x",
      "x 3g    1 x  x",
      "x444    2 x  x",
      "xg g   ggg   x",
      "xxx     xxx  x",
      "xxx     xxx  x",
      "xxx     xxx  x",
      "xxx          x",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 1,
          y: 1,
          dir: 'right'
        },
        {
          x: 3,
          y: 2,
          dir: 'left'
        },
        {
          x: 1,
          y: 4,
          dir: 'up'
        },
        {
          x: 3,
          y: 4,
          dir: 'up'
        },
        {
          x: 8,
          y: 4,
          dir: 'up'
        },
        {
          x: 7,
          y: 1,
          dir: 'right'
        },
        {
          x: 9,
          y: 1,
          dir: 'left'
        }
      ]
    ],
    [
      // Level 20
      ["xxxxxxxxxxxxxx",
      "xrrrr   rggxxx",
      "xxxb    xxxxxx",
      "xxxx       xbx",
      "xx           x",
      "xx           x",
      "xx     x     x",
      "xx x         x",
      "xx        x  x",
      "xxxxxxxxxxxxxx"],
      [
        {
          x: 12,
          y: 3,
          dir: 'up'
        }
      ]
    ]
  ];

  CELL_SIZE = 48;

  moveToCell = function(dom, x, y) {
    dom.style.left = x * CELL_SIZE + 'px';
    return dom.style.top = y * CELL_SIZE + 'px';
  };

  //#######################################
  // Game layer — pure logic, no DOM
  //#######################################
  BORDERS = {
    'left': ['borderLeft', 'borderRight'],
    'right': ['borderRight', 'borderLeft'],
    'up': ['borderTop', 'borderBottom'],
    'down': ['borderBottom', 'borderTop']
  };

  GameCell = class GameCell {
    constructor(color1, x1, y1) {
      this.color = color1;
      this.x = x1;
      this.y = y1;
      this.jelly = null;
      this.color_master = this;
      this.color_mates = [this];
    }

    mergeWith(other, dir) {
      var cell, k, len, other_master, ref;
      if (other instanceof Wall) {
        // If merging with wall, jelly becomes immovable.
        this.jelly.immovable = true;
      }
      // If merging with jelly, unify the jellies and color mates' lists.
      if (other instanceof GameCell && this.color === other.color && this.color_master !== other.color_master) {
        other_master = other.color_master;
        ref = other_master.color_mates;
        for (k = 0, len = ref.length; k < len; k++) {
          cell = ref[k];
          cell.color_master = this.color_master;
        }
        this.color_master.color_mates = this.color_master.color_mates.concat(other_master.color_mates);
      }
      if (other instanceof GameCell && this.jelly !== other.jelly) {
        return this.jelly.merge(other.jelly);
      }
    }

  };

  GameJelly = class GameJelly {
    constructor(cell) {
      cell.jelly = this;
      this.cells = [cell];
      this.immovable = false;
    }

    cellCoords() {
      var cell, k, len, ref, results;
      ref = this.cells;
      results = [];
      for (k = 0, len = ref.length; k < len; k++) {
        cell = ref[k];
        results.push([cell.x, cell.y, cell]);
      }
      return results;
    }

    updatePosition(dx, dy) {
      var cell, k, len, ref, results;
      ref = this.cells;
      results = [];
      for (k = 0, len = ref.length; k < len; k++) {
        cell = ref[k];
        cell.x += dx;
        results.push(cell.y += dy);
      }
      return results;
    }

    merge(other) {
      var cell, k, len, ref;
      ref = other.cells;
      for (k = 0, len = ref.length; k < len; k++) {
        cell = ref[k];
        this.cells.push(cell);
        cell.jelly = this;
      }
      if (other.immovable) {
        this.immovable = true;
      }
      other.cells = null;
    }

  };

  GameState = class GameState {
    constructor() {
      this.cells = null;
      this.jellies = [];
      this.num_monochromatic_blocks = 0;
      this.num_colors = 0;
      this.silent = false;
    }

    move(jellies, dx, dy) {
      var cell, jelly, k, l, len, len1, len2, len3, len4, m, n, o, ref, ref1, x, y;
      for (k = 0, len = jellies.length; k < len; k++) {
        jelly = jellies[k];
        ref = jelly.cellCoords();
        for (l = 0, len1 = ref.length; l < len1; l++) {
          [x, y, cell] = ref[l];
          this.cells[y][x] = null;
        }
      }
      for (m = 0, len2 = jellies.length; m < len2; m++) {
        jelly = jellies[m];
        jelly.updatePosition(dx, dy);
      }
      for (n = 0, len3 = jellies.length; n < len3; n++) {
        jelly = jellies[n];
        ref1 = jelly.cellCoords();
        for (o = 0, len4 = ref1.length; o < len4; o++) {
          [x, y, cell] = ref1[o];
          this.cells[y][x] = cell;
        }
      }
    }

    checkFilled(jellies, dx, dy) {
      var cell, done, jelly, k, l, len, len1, next, ref, ref1, x, y;
      done = false;
      while (!done) {
        done = true;
        for (k = 0, len = jellies.length; k < len; k++) {
          jelly = jellies[k];
          if (jelly.immovable) {
            return true;
          }
          ref = jelly.cellCoords();
          for (l = 0, len1 = ref.length; l < len1; l++) {
            [x, y, cell] = ref[l];
            next = this.cells[y + dy][x + dx];
            if (!next) { // empty space
              continue;
            }
            if (!next.jelly) { // wall
              return true;
            }
            if (ref1 = next.jelly, indexOf.call(jellies, ref1) >= 0) {
              continue;
            }
            jellies.push(next.jelly);
            done = false;
            break;
          }
        }
      }
      return false;
    }

    doSlide(jelly, dir) {
      var jellies;
      jellies = [jelly];
      if (this.checkFilled(jellies, dir, 0)) {
        return null;
      }
      this.move(jellies, dir, 0);
      return {
        jellies: jellies,
        dx: dir
      };
    }

    doFalls() {
      var dy, falls, jelly, jellyset, k, l, len, len1, len2, m, oldY, preFall, ref, ref1, ref2, try_again;
      preFall = new Map();
      ref = this.jellies;
      for (k = 0, len = ref.length; k < len; k++) {
        jelly = ref[k];
        preFall.set(jelly, jelly.cells[0].y);
      }
      try_again = true;
      while (try_again) {
        try_again = false;
        ref1 = this.jellies;
        for (l = 0, len1 = ref1.length; l < len1; l++) {
          jelly = ref1[l];
          jellyset = [jelly];
          if (!this.checkFilled(jellyset, 0, 1)) {
            this.move(jellyset, 0, 1);
            try_again = true;
          }
        }
      }
      falls = [];
      ref2 = this.jellies;
      for (m = 0, len2 = ref2.length; m < len2; m++) {
        jelly = ref2[m];
        oldY = preFall.get(jelly);
        dy = jelly.cells[0].y - oldY;
        if (dy > 0) {
          falls.push({jelly, dy});
        }
      }
      return falls;
    }

    doMerges() {
      var merges, rec;
      merges = [];
      while (true) {
        rec = this.doOneMerge();
        if (!rec) {
          break;
        }
        merges.push(rec);
      }
      if (merges.length > 0) {
        this.checkForCompletion();
      }
      return merges;
    }

    doOneMerge() {
      var cell, dir, dx, dy, jelly, k, l, len, len1, len2, m, other, rec, ref, ref1, ref2, sameJelly, x, y;
      ref = this.jellies;
      for (k = 0, len = ref.length; k < len; k++) {
        jelly = ref[k];
        ref1 = jelly.cellCoords();
        for (l = 0, len1 = ref1.length; l < len1; l++) {
          [x, y, cell] = ref1[l];
          ref2 = [[1, 0, 'right'], [0, 1, 'down']];
          for (m = 0, len2 = ref2.length; m < len2; m++) {
            [dx, dy, dir] = ref2[m];
            other = this.cells[y + dy][x + dx];
            if (!(other && other instanceof GameCell)) {
              continue;
            }
            if (cell['merged' + dir]) {
              continue;
            }
            if (other.color !== cell.color) {
              continue;
            }
            sameJelly = jelly === other.jelly;
            rec = {
              cell: cell,
              other: other,
              dir: dir,
              sameJelly: sameJelly,
              absorbedJelly: sameJelly ? null : other.jelly,
              absorbedCells: sameJelly ? null : other.jelly.cells.slice(),
              absorberImmovable: jelly.immovable,
              differentMaster: cell.color_master !== other.color_master,
              cellMaster: cell.color_master,
              cellMates: cell.color_master.color_mates.slice(),
              otherMaster: other.color_master,
              otherMates: other.color_master.color_mates.slice()
            };
            if (jelly !== other.jelly) {
              this.jellies = this.jellies.filter(function(j) {
                return j !== other.jelly;
              });
            }
            if (cell.color_master !== other.color_master) {
              this.num_monochromatic_blocks -= 1;
            }
            cell.mergeWith(other, dir);
            cell['merged' + dir] = true;
            return rec;
          }
        }
      }
      return null;
    }

    tryMove(jelly, dir) {
      var falls, merges, slide;
      slide = this.doSlide(jelly, dir);
      if (!slide) {
        return null;
      }
      falls = this.doFalls();
      merges = this.doMerges();
      return {slide, falls, merges};
    }

    undoMerges(merges) {
      var absorbedSet, absorber, cell, i, k, l, len, len1, m, rec, ref, ref1, ref2;
      for (i = k = ref = merges.length - 1; k >= 0; i = k += -1) {
        rec = merges[i];
        delete rec.cell['merged' + rec.dir];
        if (rec.differentMaster) {
          this.num_monochromatic_blocks += 1;
          ref1 = rec.otherMates;
          for (l = 0, len = ref1.length; l < len; l++) {
            cell = ref1[l];
            cell.color_master = rec.otherMaster;
          }
          rec.cellMaster.color_mates = rec.cellMates.slice();
          rec.otherMaster.color_mates = rec.otherMates.slice();
        }
        if (!rec.sameJelly) {
          absorber = rec.cell.jelly;
          absorbedSet = new Set(rec.absorbedCells);
          absorber.cells = absorber.cells.filter(function(c) {
            return !absorbedSet.has(c);
          });
          rec.absorbedJelly.cells = rec.absorbedCells;
          ref2 = rec.absorbedCells;
          for (m = 0, len1 = ref2.length; m < len1; m++) {
            cell = ref2[m];
            cell.jelly = rec.absorbedJelly;
          }
          absorber.immovable = rec.absorberImmovable;
          this.jellies.push(rec.absorbedJelly);
        }
      }
    }

    undoFalls(falls) {
      var cell, dy, jelly, k, l, len, len1, len2, len3, len4, m, n, o, ref, ref1, x, y;
      if (falls.length === 0) {
        return;
      }
      for (k = 0, len = falls.length; k < len; k++) {
        ({jelly} = falls[k]);
        ref = jelly.cellCoords();
        for (l = 0, len1 = ref.length; l < len1; l++) {
          [x, y, cell] = ref[l];
          this.cells[y][x] = null;
        }
      }
      for (m = 0, len2 = falls.length; m < len2; m++) {
        ({jelly, dy} = falls[m]);
        jelly.updatePosition(0, -dy);
      }
      for (n = 0, len3 = falls.length; n < len3; n++) {
        ({jelly} = falls[n]);
        ref1 = jelly.cellCoords();
        for (o = 0, len4 = ref1.length; o < len4; o++) {
          [x, y, cell] = ref1[o];
          this.cells[y][x] = cell;
        }
      }
    }

    undoSlide(slide) {
      this.move(slide.jellies, -slide.dx, 0);
    }

    clone() {
      var c, cell, cellMap, i, jelly, k, l, len, len1, len2, len3, m, master, masterMap, n, newCell, newJelly, ref, ref1, ref2, ref3, row, state;
      state = new GameState();
      state.silent = true;
      cellMap = new Map();
      ref = this.jellies;
      // Clone all game cells.
      for (k = 0, len = ref.length; k < len; k++) {
        jelly = ref[k];
        ref1 = jelly.cells;
        for (l = 0, len1 = ref1.length; l < len1; l++) {
          cell = ref1[l];
          newCell = new GameCell(cell.color, cell.x, cell.y);
          if (cell['mergedright']) {
            newCell['mergedright'] = true;
          }
          if (cell['mergeddown']) {
            newCell['mergeddown'] = true;
          }
          cellMap.set(cell, newCell);
        }
      }
      // Clone jellies.
      state.jellies = (function() {
        var len2, m, n, ref2, ref3, results;
        ref2 = this.jellies;
        results = [];
        for (m = 0, len2 = ref2.length; m < len2; m++) {
          jelly = ref2[m];
          newJelly = new GameJelly(cellMap.get(jelly.cells[0]));
          for (i = n = 1, ref3 = jelly.cells.length; (1 <= ref3 ? n < ref3 : n > ref3); i = 1 <= ref3 ? ++n : --n) {
            c = cellMap.get(jelly.cells[i]);
            c.jelly = newJelly;
            newJelly.cells.push(c);
          }
          newJelly.immovable = jelly.immovable;
          results.push(newJelly);
        }
        return results;
      }).call(this);
      // Fix up color_master and rebuild color_mates.
      masterMap = new Map();
      ref2 = this.jellies;
      for (m = 0, len2 = ref2.length; m < len2; m++) {
        jelly = ref2[m];
        ref3 = jelly.cells;
        for (n = 0, len3 = ref3.length; n < len3; n++) {
          cell = ref3[n];
          newCell = cellMap.get(cell);
          newCell.color_master = cellMap.get(cell.color_master);
          master = newCell.color_master;
          if (!masterMap.has(master)) {
            masterMap.set(master, []);
          }
          masterMap.get(master).push(newCell);
        }
      }
      masterMap.forEach(function(mates, master) {
        return master.color_mates = mates;
      });
      // Clone cells grid (Walls and nulls are shared).
      state.cells = (function() {
        var len4, o, ref4, results;
        ref4 = this.cells;
        results = [];
        for (o = 0, len4 = ref4.length; o < len4; o++) {
          row = ref4[o];
          results.push((function() {
            var len5, p, results1;
            results1 = [];
            for (p = 0, len5 = row.length; p < len5; p++) {
              cell = row[p];
              if (cellMap.has(cell)) {
                results1.push(cellMap.get(cell));
              } else {
                results1.push(cell);
              }
            }
            return results1;
          })());
        }
        return results;
      }).call(this);
      state.num_monochromatic_blocks = this.num_monochromatic_blocks;
      state.num_colors = this.num_colors;
      return state;
    }

    checkForCompletion() {
      if (this.silent) {
        return;
      }
      if (this.num_monochromatic_blocks <= this.num_colors) {
        alert("Congratulations! Level completed.");
      }
    }

  };

  //#######################################
  // View layer — DOM, events, animation
  //#######################################
  Wall = class Wall {
    constructor(dom1) {
      this.dom = dom1;
    }

  };

  Stage = class Stage {
    constructor(dom1, map) {
      var event, k, len, maybeSwallowEvent, merges, ref;
      this.dom = dom1;
      this.game = new GameState();
      this.history = [];
      this.busy = false;
      this.loadMap(map);
      maybeSwallowEvent = (e) => {
        e.preventDefault();
        if (this.busy) {
          return e.stopPropagation();
        }
      };
      ref = ['contextmenu', 'click', 'touchstart', 'touchmove'];
      for (k = 0, len = ref.length; k < len; k++) {
        event = ref[k];
        this.dom.addEventListener(event, maybeSwallowEvent, true);
      }
      // Initial merges from level setup (not recorded in history).
      merges = this.game.doMerges();
      this.applyMergeVisuals(merges);
    }

    loadMap(map) {
      var anchors, cell, classname, color, colors, jelly, row, table, td, tr, x, y;
      anchors = [];
      if (map[0] instanceof Array) {
        anchors = map[1];
        map = map[0];
      }
      table = document.createElement('table');
      this.dom.appendChild(table);
      colors = {};
      this.game.cells = (function() {
        var k, ref, results;
        results = [];
        for (y = k = 0, ref = map.length; (0 <= ref ? k < ref : k > ref); y = 0 <= ref ? ++k : --k) {
          row = map[y].split('');
          tr = document.createElement('tr');
          table.appendChild(tr);
          results.push((function() {
            var l, ref1, results1;
            results1 = [];
            for (x = l = 0, ref1 = row.length; (0 <= ref1 ? l < ref1 : l > ref1); x = 0 <= ref1 ? ++l : --l) {
              color = null;
              classname = 'transparent';
              cell = null;
              td = document.createElement('td');
              switch (row[x]) {
                case 'x':
                  classname = 'cell wall';
                  cell = new Wall(td);
                  break;
                case 'r':
                  color = 'red';
                  break;
                case 'g':
                  color = 'green';
                  break;
                case 'b':
                  color = 'blue';
                  break;
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                  color = 'black' + row[x];
              }
              td.className = classname;
              tr.appendChild(td);
              if (color) {
                cell = new GameCell(color, x, y);
                jelly = new GameJelly(cell);
                // Create DOM for this cell.
                cell.dom = document.createElement('div');
                cell.dom.className = 'cell jelly ' + color;
                moveToCell(cell.dom, x, y);
                this.dom.appendChild(cell.dom);
                this.addCellHandlers(cell);
                this.game.jellies.push(jelly);
                this.game.num_monochromatic_blocks += 1;
                if (!(color in colors)) {
                  this.game.num_colors += 1;
                }
                colors[color] = 1;
              }
              results1.push(cell);
            }
            return results1;
          }).call(this));
        }
        return results;
      }).call(this);
      this.addBorders();
      this.placeAnchors(anchors);
    }

    addCellHandlers(cell) {
      var stage;
      stage = this;
      cell.dom.addEventListener('contextmenu', function(e) {
        return stage.trySlide(cell.jelly, 1);
      });
      cell.dom.addEventListener('click', function(e) {
        return stage.trySlide(cell.jelly, -1);
      });
      cell.dom.addEventListener('touchstart', function(e) {
        return cell.jelly.start = e.touches[0].pageX;
      });
      return cell.dom.addEventListener('touchmove', function(e) {
        var dx;
        dx = e.touches[0].pageX - cell.jelly.start;
        if (Math.abs(dx) > 10) {
          dx = Math.max(Math.min(dx, 1), -1);
          return stage.trySlide(cell.jelly, dx);
        }
      });
    }

    placeAnchors(anchors) {
      var anchor, anchorColors, arrow, classname, directions, dx, dy, jelly, k, len, me, other, property;
      directions = {
        'left': [-1, 0, 'leftarrow', 'borderRightColor'],
        'right': [1, 0, 'rightarrow', 'borderLeftColor'],
        'up': [0, -1, 'uparrow', 'borderBottomColor'],
        'down': [0, 1, 'downarrow', 'borderTopColor']
      };
      anchorColors = {
        'red': 'hsl(0, 100%, 75%)',
        'green': 'hsl(120, 100%, 45%)',
        'blue': 'hsl(216, 100%, 70%)'
      };
      for (k = 0, len = anchors.length; k < len; k++) {
        anchor = anchors[k];
        dx = directions[anchor.dir][0];
        dy = directions[anchor.dir][1];
        classname = directions[anchor.dir][2];
        property = directions[anchor.dir][3];
        me = this.game.cells[anchor.y][anchor.x];
        other = this.game.cells[anchor.y + dy][anchor.x + dx];
        me.mergeWith(other, anchor.dir);
        // Remove borders visually for anchor merges.
        if (me.dom) {
          me.dom.style[BORDERS[anchor.dir][0]] = 'none';
        }
        if (other.dom) {
          other.dom.style[BORDERS[anchor.dir][1]] = 'none';
        }
        // Create the overlapping anchoring triangle.
        arrow = document.createElement('div');
        arrow.style[property] = anchorColors[me.color];
        arrow.className = classname;
        other.dom.appendChild(arrow);
      }
      return this.game.jellies = (function() {
        var l, len1, ref, results;
        ref = this.game.jellies;
        results = [];
        for (l = 0, len1 = ref.length; l < len1; l++) {
          jelly = ref[l];
          if (jelly.cells) {
            results.push(jelly);
          }
        }
        return results;
      }).call(this);
    }

    addBorders() {
      var attr, border, cell, dx, dy, edges, k, l, len, m, other, ref, ref1, ref2, ref3, x, y;
      for (y = k = 0, ref = this.game.cells.length; (0 <= ref ? k < ref : k > ref); y = 0 <= ref ? ++k : --k) {
        for (x = l = 0, ref1 = this.game.cells[0].length; (0 <= ref1 ? l < ref1 : l > ref1); x = 0 <= ref1 ? ++l : --l) {
          cell = this.game.cells[y][x];
          if (!(cell instanceof Wall)) {
            continue;
          }
          border = 'solid 1px #777';
          edges = [['borderBottom', 0, 1], ['borderTop', 0, -1], ['borderLeft', -1, 0], ['borderRight', 1, 0]];
          for (m = 0, len = edges.length; m < len; m++) {
            [attr, dx, dy] = edges[m];
            if (!((0 <= (ref2 = y + dy) && ref2 < this.game.cells.length))) {
              continue;
            }
            if (!((0 <= (ref3 = x + dx) && ref3 < this.game.cells[0].length))) {
              continue;
            }
            other = this.game.cells[y + dy][x + dx];
            if (!(other instanceof Wall)) {
              cell.dom.style[attr] = border;
            }
          }
        }
      }
    }

    syncDOM() {
      var cell, jelly, k, l, len, len1, ref, ref1;
      ref = this.game.jellies;
      for (k = 0, len = ref.length; k < len; k++) {
        jelly = ref[k];
        ref1 = jelly.cells;
        for (l = 0, len1 = ref1.length; l < len1; l++) {
          cell = ref1[l];
          if (cell.dom) {
            moveToCell(cell.dom, cell.x, cell.y);
          }
        }
      }
    }

    applyMergeVisuals(merges) {
      var k, len, rec;
      for (k = 0, len = merges.length; k < len; k++) {
        rec = merges[k];
        if (rec.cell.dom) {
          rec.cell.dom.style[BORDERS[rec.dir][0]] = 'none';
        }
        if (rec.other.dom) {
          rec.other.dom.style[BORDERS[rec.dir][1]] = 'none';
        }
      }
    }

    undoMergeVisuals(merges) {
      var i, k, rec, ref;
      for (i = k = ref = merges.length - 1; k >= 0; i = k += -1) {
        rec = merges[i];
        if (rec.cell.dom) {
          rec.cell.dom.style[BORDERS[rec.dir][0]] = '';
        }
        if (rec.other.dom) {
          rec.other.dom.style[BORDERS[rec.dir][1]] = '';
        }
      }
    }

    waitForAnimation(cb) {
      var end, k, len, name, names;
      names = ['transitionend', 'webkitTransitionEnd'];
      end = () => {
        var k, len, name;
        for (k = 0, len = names.length; k < len; k++) {
          name = names[k];
          this.dom.removeEventListener(name, end);
        }
        return setTimeout(cb, 0);
      };
      for (k = 0, len = names.length; k < len; k++) {
        name = names[k];
        this.dom.addEventListener(name, end);
      }
    }

    trySlide(jelly, dir) {
      var slide, turn;
      if (this.busy) {
        return;
      }
      slide = this.game.doSlide(jelly, dir);
      if (!slide) {
        return;
      }
      this.busy = true;
      turn = {slide};
      this.history.push(turn);
      this.syncDOM();
      return this.waitForAnimation(() => {
        var afterFall;
        turn.falls = this.game.doFalls();
        this.syncDOM();
        afterFall = () => {
          turn.merges = this.game.doMerges();
          this.applyMergeVisuals(turn.merges);
          return this.busy = false;
        };
        if (turn.falls.length > 0) {
          return this.waitForAnimation(afterFall);
        } else {
          return afterFall();
        }
      });
    }

    undo() {
      var turn, undoSlideStep;
      if (this.busy || this.history.length === 0) {
        return;
      }
      this.busy = true;
      turn = this.history.pop();
      // Step 1: Undo merge visuals + game state.
      this.undoMergeVisuals(turn.merges);
      this.game.undoMerges(turn.merges);
      // Step 2: Undo falls (animated).
      this.game.undoFalls(turn.falls);
      this.syncDOM();
      undoSlideStep = () => {
        // Step 3: Undo slide (animated).
        this.game.undoSlide(turn.slide);
        this.syncDOM();
        return this.waitForAnimation(() => {
          return this.busy = false;
        });
      };
      if (turn.falls.length > 0) {
        return this.waitForAnimation(undoSlideStep);
      } else {
        return undoSlideStep();
      }
    }

  };

  //#######################################
  // Initialization
  //#######################################
  level = parseInt(location.search.substr(1), 10) || 1;

  stage = new Stage(document.getElementById('map'), levels[level - 1]);

  window.stage = stage;

  levelPicker = document.getElementById('level');

  for (i = k = 1, ref = levels.length; (1 <= ref ? k <= ref : k >= ref); i = 1 <= ref ? ++k : --k) {
    option = document.createElement('option');
    option.value = i;
    option.appendChild(document.createTextNode(`Level ${i}`));
    levelPicker.appendChild(option);
  }

  levelPicker.value = level;

  levelPicker.addEventListener('change', function() {
    return location.search = '?' + levelPicker.value;
  });

  undoHandler = function() {
    return stage.undo();
  };

  document.getElementById('undo').addEventListener('click', undoHandler);

  document.addEventListener('keydown', function(e) {
    if (e.key === 'Backspace') {
      return undoHandler();
    }
  });

  document.getElementById('reset').addEventListener('click', function() {
    stage.dom.innerHTML = '';
    return stage = new Stage(stage.dom, levels[level - 1]);
  });

}).call(this);
